### ISSUE TITLE
[Faq] Verificar esse bug em outros modulos do sistema

### ISSUE THREAD

**Issue by rafaelfigueredog** [IST-Stenio-Lopes/painel-matricula#26]
### Passos para reprodução.

1. Entrar em faq, 
2. Criar um tópico com titulo: **What is Lorem Ipsum?**
3. Deletar esse tópico 
4. Tentar criar outro tópico com o mesmo título

#### A seguinte mensagem será mostrada no modal: 

![Image](https://user-images.githubusercontent.com/34730673/190654965-b0dcbc8e-8d2c-4ed1-ae91-931e891781d1.png)

Esse erro pode estar acontecendo porque a remoção está sendo feita em nível lógico, seria interessante verificar se o erro ocorre em outros módulos do sistema.

**Comment by IST-Stenio-Lopes** [comment]
Foi adicionada uma verificação na validação para checar se o FAQ está com o status de removido.
